# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: Silversoft.speed
PackageVersion: "8.60"
PackageLocale: en-US
Publisher: silversoft corp
PackageName: speed
License: shareware
ShortDescription: Increase speed of your system instantly
ManifestType: defaultLocale
ManifestVersion: 1.5.0
